### PR TITLE
Added CSUSB Logo and Link to Footer

### PR DESCRIPTION
**Pull request by Cwagne17**
In this PR that completes [Story 3444](https://app.clubhouse.io/clarkcan/story/3444/add-csusb-logo-to-footer)

The CSUSB Logo 

was added to the footer.

Screen Shot 2021-01-22 at 2 24 07 PM

It is mobile friendly also.

Screen Shot 2021-01-22 at 2 24 44 PM

### CODE REVIEW

**Review by pzalep1 — COMMENTED** [review]
Can we move it to the right of the NCyTE logo?

**Review by EVogel1999 — COMMENTED** [review]
After Paige's comment looks good.

**Comment by Cwagne17** [comment]
Here is after the change
Screen Shot 2021-01-25 at 8 09 29 AM

Screen Shot 2021-01-25 at 8 08 40 AM

**Review by pzalep1 — APPROVED** [review]
Thank you!

**Review by jmulholland4014 — APPROVED** [review]

**Review by EVogel1999 — APPROVED** [review]

**Pull request merged**
