### PR TITLE
Feature/sc 32781/submissions module route updates for clark

### PR DESCRIPTION
**Pull request by Romerico234**
Removed SUBMIT_LEARNING_OBJECT route from learning-object.service.ts--a function already exists in submissions.service.ts. GET_SUBMISSIONS route has no reference

### CODE REVIEW

**Review by Cwagne17 — COMMENTED** [review]
Can you rebase then re-request.

**Review by pzalep1 — COMMENTED** [review]
When you fix the other branches that are also failing the build make sure that you pull those changes into this branch and then the build will start working.

**Comment by Romerico234** [comment]
> You mention that GET_SUBMISSIONS is not used. I don't see that in the file changes.
> 
> Also did you check that the submitLearningObject in submissions.service.ts is being used?

I removed the GET_SUBMISSIONS route, and there were no build issues. For submitLearningObject, it is being used in these  two locations:
- /clark-client/src/app/onion/dashboard/dashboard.component.ts
- /clark-client/src/app/onion/shared/submit/submit.component.ts

**Review by pzalep1 — COMMENTED** [review]
The code and build appear to be fine, but for some reason the lint job is unable to run and the zip step on the build is not finding a specific library. It does look like CircleCI is having an outage, but this might be a different issue. I would just take a look at the branch you're looking to merge into.

**Review by Greek — APPROVED** [review]

**Review by pzalep1 — APPROVED** [review]

**Review by Cwagne17 — APPROVED** [review]

**Review by johngonz0 — COMMENTED** [review]
I may be wrong, but on my end, `CHECK_FIRST_SUBMISSION, SUBMIT, and UNSUBMIT `also exists in the user routes  of routes.ts file. I dont know if were touching these, but there are references to some of these routes on the client as `USER_ROUTES.CHECK_FIRST_SUBMISSION`

@pzalep1 @Cwagne17 are we touching this file?

**Pull request merged**
