### PR TITLE
Check for width and truncate collection

### LINKED ISSUE #621: Remove "community" from name of collection
Remove the third word from name of "secure coding community" collection. Too long. breaks UI. 
screen shot 2019-02-13 at 7 50 03 pm

### PR DESCRIPTION
**Pull request by EVogel1999**
Sets the collection div on a learning object card to a window resize event.  If the screen width is less than 750 pixels then it will truncate the collection name and end it with ellipses.

Closes #621

### CODE REVIEW

**Comment by EVogel1999** [comment]
Screen Shot 2019-03-15 at 9 56 57 AM
Screen Shot 2019-03-15 at 9 57 17 AM
Screen Shot 2019-03-15 at 9 57 42 AM
Screen Shot 2019-03-15 at 9 57 53 AM

**Comment by EVogel1999** [comment]
Before:
Screen Shot 2019-03-15 at 10 20 01 AM

**Comment by nrwinner** [comment]
It looks like, with truncation, the flag still extends past the outer bounds of the image. Can we perhaps truncate additionally? Or maybe just finagle with the CSS to move that flag corner in a bit.

**Comment by EVogel1999** [comment]
image

**Pull request merged**
