### PR TITLE
Fixed plus minus on the details page

### PR DESCRIPTION
**Pull request by stef359**

### CODE REVIEW

**Review by JosueMolinaMorales — CHANGES_REQUESTED** [review]
Could you add a small description of the PR and screenshots of the new changes? 
You can check out our standards for creating PR's here: https://cyber4all.github.io/cyber4all-docs/docs/dev/standards/github_standards.html#pull-requests

**Review by mfranz1 — COMMENTED** [review]
After Josue's comment is addressed just re-request me.
Implementation looks good!

**Comment by stef359** [comment]
In the hierarchy-link.components.html file I changed line 12 from checking the children variables length to checking the parents variable length.
As seen below the bug is gone.
Screenshot 2023-02-02 at 10 55 50 AM

**Review by pmanal1 — APPROVED** [review]
🤌

**Review by mfranz1 — APPROVED** [review]

**Review by bereketsega — APPROVED** [review]

**Review by pzalep1 — APPROVED** [review]

**Review by JosueMolinaMorales — APPROVED** [review]

**Review by Cwagne17 — APPROVED** [review]
Do we know how come the package-lock.json lost 17,000 lines?

**Pull request merged**
