### PR TITLE
fix details page

### PR DESCRIPTION
**Pull request by Olaniyan99**
fix the details page bug

### CODE REVIEW

**Comment by nvisal1** [comment]
> Screenshot please.

Can we get a screenshot for mobile too?

**Comment by Olaniyan99** [comment]
Screen Shot 2020-03-13 at 10 40 27 AM

**Comment by Olaniyan99** [comment]
Screen Shot 2020-03-13 at 11 02 22 AM

**Comment by Olaniyan99** [comment]
Screen Shot 2020-03-13 at 12 07 13 PM

**Comment by Olaniyan99** [comment]
Screen Shot 2020-03-13 at 12 07 18 PM

**Pull request merged**
