### PR TITLE
5th Birthday Banner

### PR DESCRIPTION
**Pull request by AStoerkel1**
This PR Relates to [14082](https://app.shortcut.com/clarkcan/story/14082/clark-5th-birthday-confetti)

Adds a Birthday banner to the new homepage for Clark's 5th Birthday. I did this with no mock and half as a joke so any comments are appreciated. 

### I designed this to be easily removable after 5th birthday is over so if it looks like ugly code, think about how easy it'll be to find and remove

https://user-images.githubusercontent.com/41537999/188877639-28e45b96-d4f1-48ca-be61-331a4db190d0.mov

https://user-images.githubusercontent.com/41537999/188877658-4c97e3d8-8cbb-473a-9f84-6f81ab66b069.mov

### CODE REVIEW

**Review by JosueMolinaMorales — APPROVED** [review]
Awesome!

**Review by mfranz1 — APPROVED** [review]

**Comment by katieblomquist** [comment]
I couldn't easily find the confetti you're using on can I use. Do you know what browser compatibility is for it? Other than my one curiosity, this looks great!

**Review by jouypo23 — APPROVED** [review]

**Comment by AStoerkel1** [comment]
> I couldn't easily find the confetti you're using on can I use. Do you know what browser compatibility is for it? Other than my one curiosity, this looks great!

here is the link to their github, doesn't say anything about browser compatibility

**Review by pmanal1 — APPROVED** [review]
🎉 🎊

**Pull request merged**
