### PR TITLE
Refactor filterSearchComponent to send a single request

### PR DESCRIPTION
**Pull request by stef359**
This PR refactors the filterSearchComponent to send a single request all together for the filters applied, instead of multiple requests for each filter applied.

Story details: https://app.shortcut.com/clarkcan/story/32835/refactor-filtersearchcomponent-to-send-a-single-search-request-when-applying-queries

### CODE REVIEW

**Review by pzalep1 — COMMENTED** [review]
Can we get a video of the filters? Thanks!

**Comment by johngonz0** [comment]
> Can we get a video of the filters? Thanks!

+1

**Comment by stef359** [comment]
https://github.com/user-attachments/assets/4c559eb1-cda9-4b78-96dd-a504b641cc4a

**Review by pzalep1 — APPROVED** [review]

**Review by dsoto18 — APPROVED** [review]
Nice work

**Review by joaquinVill — APPROVED** [review]

**Review by johngonz0 — APPROVED** [review]

**Pull request merged**
